---
title: "ESM 204 HW 3"
author: "Sarah Hamilton, Carleigh Osen, and Maggie Hammond"
date: "5/2/2022"
output: 
  html_document:
    theme: flatly
    code_folding: hide
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(equatiomatic)
library(broom)
library(ggpubr)

```


```{r}
co2_cost <- read_csv(here("HW3_data.csv")) %>% 
  clean_names()
```


```{r}

co2_cost_income <- co2_cost %>% 
  pivot_longer(cols = c(q_low_kwh, q_high_kwh),
               names_to = 'income',
               values_to = 'q_kwh') %>% 
  mutate(income = case_when(
    income == "q_low_kwh" ~ "Low",
    income == "q_high_kwh" ~ "High"
  ))
```


# Create Marginal Demand Linear Regression Model

```{r}
low_lm <- lm(price_cents ~ q_low_kwh, 
             data = co2_cost)

# coefficients: intercept 23.3709671, Q coefficient -0.0001102

high_lm <- lm(price_cents ~ q_high_kwh, 
              data = co2_cost)

# coefficients: intercept 31.61, Q coefficient -5.202e-05

extract_eq(model = low_lm, use_coefs = TRUE, coef_digits = 5)
extract_eq(model = high_lm, use_coefs = TRUE, coef_digits = 5)

low_mb <- function(x){23.37-.00011*x}
high_mb <- function(x){31.16 - 5.202e-05*x}


# to add the demands to find aggregate demand

low_lm_q <- lm(q_low_kwh ~ price_cents, 
             data = co2_cost)


high_lm_q <- lm(q_high_kwh ~ price_cents, 
             data = co2_cost)

extract_eq(model = low_lm_q, use_coefs = TRUE)
extract_eq(model = high_lm_q, use_coefs = TRUE)

# 191672.48 + 584850.4 + (-7722.83+17716.67 price)

# Qagg = 776522.88 - 25439.5P
# P agg = 776522.88/25439.5 - Q/25439.5

# FOR DEMAND AGG P = 30.52 - 3.93e-5Q

```

```{r}
#plot the functions
ggplot(data = co2_cost_income, aes(y = price_cents, x = q_kwh)) +
  geom_point(aes(color = income)) +
  scale_color_manual(values = c('orange', 'purple2')) +
  stat_function(fun = low_mb, color = "purple2") +
  stat_function(fun = high_mb, color = "orange") +
  ylim(0, 50) +
  labs(x = "Quantity kWh",
       y = "Price (cents) per kWh",
       color = "Income Level") +
  theme_minimal()
```

```{r}
#Sarah's work below
#Aggregate demand function
d_agg <- function(x){28.7-x/29091}

#MEC function
mec <- function(x){1.96}

#MPC function
mpc <- function(x){0.000018*x}

#MSC function (MPC+MEC)
msc <- function(x){0.000018*x+1.96}

#Plot all functions
ggplot(data = co2_cost_income, aes(y = price_cents, x = q_kwh)) +
  geom_point(aes(color = income)) +
  scale_color_manual(values = c('orange', 'purple2', 'yellow', 'blue', 'green', 'pink')) +
  stat_function(fun = low_mb, color = "purple2") +
  stat_function(fun = high_mb, color = "orange") +
  stat_function(fun = d_agg, color = 'yellow') +
  stat_function(fun = mec, color = 'blue') +
  stat_function(fun = mpc, color = 'green') +
  stat_function(fun = msc, color = 'pink') +
  ylim(0, 50) +
  xlim(0, 1000000) +
  labs(x = "Quantity kWh",
       y = "Price (cents) per kWh",
       color = "Income Level") +
  theme_minimal()
```

```{r}

```


